# Generated by Django 5.2.12 on 2026-04-30 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('program', models.CharField(help_text='The program this course belongs to, e.g. BSc Computer Science', max_length=150)),
                ('academic_year', models.IntegerField(help_text='Year of study e.g. 1, 2, 3')),
            ],
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='program',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.course'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='timetable.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
