# Generated by Django 5.2.12 on 2026-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_course_remove_timetableentry_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='target_class',
            field=models.CharField(blank=True, help_text='The target class from the timetable, e.g. BIT_1B', max_length=100, null=True),
        ),
    ]
