# Generated by Django 5.2.13 on 2026-04-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.IntegerField(default=1)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('facilities', models.JSONField(default=list, help_text='List of facilities like Projector, AC')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
