# Generated by Django 5.2.12 on 2026-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='free', max_length=20),
        ),
    ]
