# Generated by Django 5.2.12 on 2026-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, help_text='e.g. BSc IT, BSc CS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stream',
            field=models.CharField(blank=True, help_text='e.g. A, B, C', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_year',
            field=models.IntegerField(blank=True, help_text='Year of study (e.g., 1, 2, 3)', null=True),
        ),
    ]
